### ISSUE TITLE
Callback on flash message close

### ISSUE THREAD

**Issue by gidomanders** [42BV/react-flash-messages#10]
I have a case where the page should be reloaded after a success message is displayed. Without the reload, the application doesn't work correctly. Without the success message, it's not clear to the user that the form was successfully submitted.

**Comment by MrHus** [comment]
Lets create a callback called `onRemoved`, it should have the following signature:

```ts
export type Reason = 'duration-elapsed' | 'manually-removed';
export type OnFlashMessageRemoved<Data> = (msg: FlashMessage<Data>, reason: Reason) => void;
```
